name: PremiumAutoLogin
version: 1.0-SNAPSHOT
main: me.siryq.premiumautologin.PremiumAutoLogin
api-version: '1.21'
depend: [AuthMe]
authors: [Siryq]
description: Esegue l'autologin con AuthMe per gli utenti Premium verificati.